### ISSUE TITLE
ImportError: No module named OwlSettings

### ISSUE THREAD

**Issue by Foxel05** [lilith645/Overwatch-League-Token-Scripts#1]
Hey, i love your script, but i'm not able to execute it.

What i did

```
1. created an .owl folder in home
2. copied all files from the repository to the .owl folder (*.py and the Owl_Settings folder)
3. moved the file owl-settings.ini to .owl (from the folder owl_settings)
4. adjust the settings
5. pip install pyautogui selenium
6. try to run CheckChannelLive.py
```

### Error

```
user@freqtrade:/home/.owl# python CheckChannelLive.py
Traceback (most recent call last):
File "CheckChannelLive.py", line 2, in <module>
from OwlSettings import settings as owl_settings;
ImportError: No module named OwlSettings
```

**Comment by Owlkaline** [comment]
Hi,

Thanks for the kind words and sorry for the late reply.

I really should update this repository, however, just based on the information you have given, I believe the issue might be because the folder inside the $HOME/.owl folder is name `owl_settings` rather than 'OwlSettings'.

 So the output of 'pwd' command while in the OwlSettings folder should look something like this:
 
 ```
 $HOME/.owl/OwlSettings
 ```
 
This probably isn't your issue as you did say you copied the files and folders, just let me know if it was or wasn't the issue and if you are still having issues, I'll be happy to look further into the issue for you.
